version: "3.8"

services:
  frontend:
    build: ./client
    container_name: mern_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
    networks: 
      - mern_app

  backend:
    build: ./server
    container_name: mern_backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI = "mongodb+srv://husainvijapura:mh123@mh.palj3oj.mongodb.net/?retryWrites=true&w=majority&appName=mh"
      - PORT=5000
      - IMGBB = "f00f71aa00c5346a2678f671b780f378"
      - FRONTEND_URL = "http://localhost:3000"
    restart: always
    networks: 
      - mern_app

networks:
  mern_app:
